### ISSUE TITLE
Fix invalid support info

### ISSUE THREAD

**Issue by voxpelli** [maggie0002/balena-plex-seedbox#3]
Your `.github` repository is a fork of the StandardJS one and still contains mentions of eg our Discord channel: https://github.com/maggie0002/.github/blob/77caf637abf31153fa8d97544134e038c6630ea7/.github/ISSUE_TEMPLATE/config.yml#L4

Please correct this and other unchanged info instead of eg. sending confused users to our Discord asking for help there 🙏

**Comment by maggie44** [comment]
Thanks, updated. Not even sure what that fork is there for, will just remove it :)
